### PR TITLE
fix(docs): Require field must be in quotes (PACMAN-791)

### PR DESCRIPTION
**Pull request by tore-espressif**
@magicarm22 Please check this update

I had to place "no" in quotes so it works on my Windows machine and idf-component-manager 1.4.1

### CODE REVIEW

**Comment by magicarm22** [comment]
@tore-espressif Thanks for your contribution, LGTM!

**Comment by tore-espressif** [comment]
@kumekay Here is the error log:
```
 ERROR: A problem was found in the manifest file
  C:/github_repos/esp-bsp/examples/display/main\idf_component.yml:

  Unknown boolean field "require" in the manifest file that may affect build
  result



  SUGGESTION: This component may be using a newer version of the component
  manager.

  You can try to update the component manager by running:

      C:\Espressif\python_env\idf5.3_py3.8_env\Scripts\python.exe -m pip install --upgrade idf-component-manager



Call Stack (most recent call first):
  C:/esp_repos/esp-idf/master/tools/cmake/project.cmake:710 (idf_build_process)
  CMakeLists.txt:9 (project)
  ```
  
  This is the manifest
``` yml
description: BSP Display example

dependencies:
  esp_wrover_kit:
    version: "^1.0.0"
    require: no
    override_path: "../../../bsp/esp_wrover_kit"
```

**Comment by kumekay** [comment]
@tore-espressif Thank you for the log, `no` without quotes should be supported, we will fix it

**Comment by kumekay** [comment]
@tore-espressif We fixed support for `no` without quotes in https://github.com/espressif/idf-component-manager/commit/6ae82dfbc9d90cc613e16b7b1109091a6ea58955

**Pull request closed without merging**
