### PR TITLE
Fixing submodule update issue in `git_client.py/prepare_ref method` (PACMAN-758)

### PR DESCRIPTION
**Pull request by MiguelBarro**
I discovered that *component manager* fails on github provided components using submodules in a particular usecase: the github component has submodules in `main` branch that are not present yet in the target commit.

## Impact

I updated the method that checks out the component in order to update the modules in the target (yml required) commit.

## Related links

I provide a minimal reproducer:

1. Create a new component.
1. Introduce the following dependency in its `idf_component.yml`:
```yml
dependencies:
  dummy-example/git-only-cmp:
    path: git-only-cmp
    git: https://github.com/MiguelBarro/example_components.git
    version: 7b7ffdf
...
```
1. Try to update using `idf.py update-dependencies `

This will fail with the message:
```
CMake Error at C:/ProgramData/Espressif/frameworks/esp-idf-v5.1/tools/cmake/build.cmake:540 (message):
  ERROR: Solver failed processing dependency "dummy-example/git-only-cmp"
  from the manifest file
  "C:/Users/XXXX/AppData/Local/Temp/my_component/src\idf_component.yml".

  'git --work-tree=.  -C C:\Users\XXXX\AppData\Local\Temp\tmp4y39hplb
  --git-dir
  C:\Users\XXXX\AppData\Local\Espressif\ComponentManager\Cache\b_git_515d0812
  submodule update --init --recursive' failed with exit code 128

  fatal: No url found for submodule path 'optparse' in .gitmodules
```

### Rationale

`https://github.com/MiguelBarro/example_components.git` is a fork of `https://github.com/espressif/example_components`. It merely introduces a submodule (`optparse`) in the `git-only-cmp`.
Because the new component's `idf_component.yml` references a commit that lacks this submodule there is a failure.

After some debugging I zeroed the `prepare_ref` method as the source of the issue. The following call:

https://github.com/espressif/idf-component-manager/blob/ab3f84bcda058172b57e8c77a9cf37ae81579b7f/idf_component_tools/git_client.py#L133-L139

checks out the right files but the `checkout_path` is not a real worktree path and lacks state. The following call executes in the `main` branch generating the error:

https://github.com/espressif/idf-component-manager/blob/ab3f84bcda058172b57e8c77a9cf37ae81579b7f/idf_component_tools/git_client.py#L144-L149

My workaround just:
1. creates an empty worktree in a temporary dir
1. checks out the desired files
1. updates the submodules
1. copies the contents of the temporary dir in the desired checkout path
1. remove the worktree 

The only reason to use a temporary dir is that I could not find a way to remove the worktree reference without deleting the associated directory too.

---

### Checklist

1. [x] Please provide the specific and clear title of the PR describing the change (eg. _„Fix support for python versions >3.136“_)
4. [x] Please provide related links (eg. Issue, related repository, etc...)

_This entire section above can be deleted if all items are checked._

### CODE REVIEW

**Comment by kumekay** [comment]
@MiguelBarro Thank you for opening this PR and the detailed description of the problem. We will review your PR in detail shortly.

**Comment by magicarm22** [comment]
Hi @MiguelBarro,

Apologies for the delay in reviewing your pull request. I tried your minimal reproduce code, and  I couldn't reproduce the error you mentioned.

Could you please check that error is still exists? Could provide more details how can I reproduce this error? I tried idf-component-manager v1.3, and version from a master branch. I also tried different commits from your fork repository - all these combinations solve good.

My environment:
1. ESP-IDF: v5.2-dev-3091-g217defb939
2. IDF component manager v1.3.2 or IDF component manager v1.5.0-dev0
3. Project with component `main` with `idf_component.yml` file:
```
dependencies:
  dummy-example/git-only-cmp:
    path: git-only-cmp
    git: https://github.com/MiguelBarro/example_components.git
    version: 7b7ffdf # or with version: ccc6fe8812ccbf7e5b7f5d2617576b540c04216f, or without version
```

**Comment by MiguelBarro** [comment]
I'm using windows 11:
-  esp-idf-v5.1
-  IDF Component Manager 1.3.2

I don't think the framework version makes any difference (though maybe the git version has something to do).
In order to reproduce it (I use powershell):

- Download the `examples/get-started/hello_world` from the `espressif/esp-idf` repo.
```
> idf.py create-manifest -C ./hello_world
> @'
   dummy-example/git-only-cmp:
     path: git-only-cmp
     git: https://github.com/MiguelBarro/example_components.git
     version: 7b7ffdf
 '@ | Out-File -Append .\hello_world\main\idf_component.yml
> idf.py reconfigure -C .\hello_world\
```

**Comment by magicarm22** [comment]
Hello, @MiguelBarro 

I started to test it on the Windows 11 machine. My new environment:
1. Windows 11 Pro 22631.3007
2. ESP-IDF v5.1.2
3. idf-component-manager 1.3.2 and 1.4.2
4. Git version 2.43.0.windows.1

I run all your commands, and my manifest file is:
```
## IDF Component Manager Manifest File
dependencies:
  ## Required IDF version
  idf:
    version: ">=4.1.0"
  # # Put list of dependencies here
  # # For components maintained by Espressif:
  # component: "~1.0.0"
  # # For 3rd party components:
  # username/component: ">=1.0.0,<2.0.0"
  # username2/component2:
  #   version: "~1.0.0"
  #   # For transient dependencies public flag can be set.
  #   # public flag doesn't have an effect dependencies of the main component.
  #   # All dependencies of main are public by default.
  #   public: true
  dummy-example/git-only-cmp:
     path: git-only-cmp
     git: https://github.com/MiguelBarro/example_components.git
     version: 7b7ffdf
```
And it reconfigures good:
```
...
Manifest files have changed, solving dependencies.
.....Updating lock file at C:\Espressif\frameworks\esp-idf-v5.1.2\examples\get-started\hello_world\dependencies.lock
Processing 3 dependencies:
[1/3] dummy-example/git-only-cmp (7b7ffdfcf549130205d23ed4b1843d7a32bdfce6)
[2/3] example/cmp (3.3.9)
[3/3] idf (5.1.2)
-- Project sdkconfig file C:/Espressif/frameworks/esp-idf-v5.1.2/examples/get-started/hello_world/sdkconfig
Compiler supported targets: xtensa-esp32-elf

-- Looking for sys/types.h
...
```

I apologize, but I can't reproduce it right now. Maybe, you need to clean your cache using the command `compote cache clear`, and then try again. Please, don't hesitate to ask questions and show other commands how it can be reproduced.

**Comment by MiguelBarro** [comment]
Hello @magicarm22 
I have composed an action to check it and it works: https://github.com/MiguelBarro/example_components/actions/runs/7985512214/job/21804109380
It must be my local config.
Thanks

**Pull request closed without merging**
